version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "minapp"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1qd8kihutckvl"
s3_prefix = "minapp"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
