AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Globals:
  # Workaround to stop forced creation of API Gateway stage called "Stage"
  # https://github.com/aws/serverless-application-model/issues/191#issuecomment-580412747
  Api:
    OpenApiVersion: 3.0.1

Resources:
  BasicRustFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: AB-reply
      Handler: bootstrap.is.real.handler
      Runtime: provided
      MemorySize: 128
      Timeout: 5
      CodeUri: .
      Environment:
        Variables:
          RUST_BACKTRACE: 1
      Events:
        POST:
          Type: Api
          Properties:
            Path: /ab
            Method: POST
            RestApiId: !Ref ABApi
    Metadata:
      BuildMethod: makefile

  ABApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      EndpointConfiguration:
        Type: REGIONAL